apiVersion: v1
kind: Service
metadata:
  name: mysql-57
  labels:
    app: mysql-57
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30006
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-57