apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-db
spec:
  type: NodePort
  ports:
    - name: mongo-service
      port: 27017
      nodePort: 30017
      targetPort: 27017
  selector:
    app: mongo-db